
[Allowed-Blocks]
	#Here you can add every block you like to get a Bone Meal effect applied.
	Block-List = []
	#Here you can add block Tags for easier use of this mod.
	Tag-List = ["minecraft:saplings"]

